name: picklick_customer
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1.15

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state management
  get: ^4.3.8
  get_storage:

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # Firebase
  firebase_auth: ^3.1.2
  firebase_core: ^1.7.0
  firebase_storage: ^10.0.4
  cloud_firestore: ^3.1.5

  # Notification
  firebase_messaging: "^10.0.8"
  flutter_local_notifications: ^9.0.0
  timezone: ^0.8.0

  http: ^0.13.4

  # formating
  pin_input_text_field: ^4.1.1
  intl: ^0.17.0

  # Maps

  geolocator: ^8.1.1
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.0.6
  geocoding: ^2.0.2

  # App
  url_launcher: ^6.0.12

  # Animations
  lottie: ^1.2.1
  animations: ^2.0.2

  # Payment Gateway
  razorpay_flutter: ^1.2.9

  permission_handler: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
